nav:
  # the title displays in the upper left corner which won't change
  title: LightedCode
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/lightedcode
    Search: /search

# footer items
footer:
  # the title
  LightedCode:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Tags: /tags
    Categories: /categories
    Search: /search
    About: /about
  # the title
  Me:
    # items
    GitHub: https://github.com/lightedcode
    Email: lightedcode@outlook.com

color_scheme: [light/dark/auto]
show_color_scheme_toggle: true

search: true
search_path: search.json