nav:
  title: LightedCode
  items:
    - name: Archives
      url: /archives
    - name: Tags
      url: /tags
    - name: Categories
      url: /categories
    - name: About
      url: /about
    - name: <i class="si si-github"></i>
      is_icon: true
      url: https://github.com/lightedcode
    - name: <i class="bi bi-search"></i>
      is_icon: true
      url: /search

footer:
  - group_name: Blog
    items:
      - name: Home
        url: /
      - name: Archives
        url: /archives
      - name: Tags
        url: /tags
      - name: Categories
        url: /categories
      - name: About
        url: /about
  # - group_name: Projects
  #   items:
  #     - name: Hexo Theme Cupertino
  #       url: https://github.com/MrWillCom/hexo-theme-cupertino
  #     - name: Next Mastodon Gallery
  #       url: https://github.com/MrWillCom/next-mastodon-gallery
  - group_name: Me
    items:
      - name: GitHub
        url: https://github.com/lightedcode
      - name: Email
        url: lightedcode@outlook.com

color_scheme: [light/dark/auto]
show_color_scheme_toggle: true

search: true
search_path: search.json