nav:
  # the title displays in the upper left corner which won't change
  title: LightedCode
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    About: /about
    GitHub: https://github.com/lightedcode
    Search: /search

# footer items
footer:
  Blog:
    Blog: /
    Archives: /archives
    Search: /search
    About: /about
  Projects:
  Me:
    GitHub: https://github.com/lightedcode
    Email: lightedcode@outlook.com
    
favicon: /image/favicon.png

scroll_reveal: true

color_scheme: [light/dark/auto]
show_color_scheme_toggle: true

search: true
search_path: search.json